export default {
  INBOUND: {
    type: 'inbound',
    field: 'count',
    icon: 'ws-widget-inbound',
    locale: 'widgets.inbound',
    show: true,
  },
  HANDLES: {
    type: 'handles',
    field: 'handles',
    icon: 'ws-widget-handles',
    locale: 'widgets.handles',
    show: true,
  },
  MISSED: {
    type: 'missed',
    field: 'abandoned',
    icon: 'ws-widget-missed',
    locale: 'widgets.missed',
    show: true,
  },
  AVG_TALK: {
    type: 'avgTalk',
    field: 'avgTalkSec',
    icon: 'ws-widget-avg-talk',
    locale: 'widgets.avgTalk',
    show: true,
  },
  AVG_HOLD: {
    type: 'avgHold',
    field: 'avgHoldSec',
    icon: 'ws-widget-avg-hold',
    locale: 'widgets.avgHold',
    show: true,
  },
  OCCUPANCY: {
    type: 'occupancy',
    field: 'occupancy',
    icon: 'ws-widget-occupancy',
    locale: 'widgets.occupancy',
    show: true,
  },
  UTILIZATION: {
    type: 'utilization',
    field: 'utilization',
    icon: 'ws-widget-utilization',
    locale: 'widgets.utilization',
    show: true,
  },
  CHAT_ACCEPTS: {
    type: 'chatAccepts',
    field: 'chatAccepts',
    icon: 'ws-widget-chat-accepts',
    locale: 'widgets.chatAccepts',
    show: true,
  },
  CHAT_AHT: {
    type: 'chatAht',
    field: 'chatAht',
    icon: 'ws-widget-chat-aht',
    locale: 'widgets.chatAht',
    show: true,
  },
};
