export default {
  INBOUND: {
    type: 'callInbound',
    field: 'callInbound',
    icon: 'ws-widget-call-inbound',
    locale: 'widgets.callInbound',
    show: true,
  },
  HANDLED: {
    type: 'callHandled',
    field: 'callHandled',
    icon: 'ws-widget-call-handled',
    locale: 'widgets.callHandled',
    show: true,
  },
  MISSED: {
    type: 'callMissed',
    field: 'callMissed',
    icon: 'ws-widget-call-missed',
    locale: 'widgets.callMissed',
    show: true,
  },
  AVG_TALK: {
    type: 'avgTalk',
    field: 'avgTalkSec',
    icon: 'ws-widget-avg-talk',
    locale: 'widgets.avgTalk',
    show: false,
  },
  AVG_HOLD: {
    type: 'avgHold',
    field: 'avgHoldSec',
    icon: 'ws-widget-avg-hold',
    locale: 'widgets.avgHold',
    show: false,
  },
  OCCUPANCY: {
    type: 'occupancy',
    field: 'occupancy',
    icon: 'ws-widget-occupancy',
    locale: 'widgets.occupancy',
    show: false,
  },
  UTILIZATION: {
    type: 'utilization',
    field: 'utilization',
    icon: 'ws-widget-utilization',
    locale: 'widgets.utilization',
    show: false,
  },
  CHAT_ACCEPTS: {
    type: 'chatAccepts',
    field: 'chatAccepts',
    icon: 'ws-widget-chat-accepts',
    locale: 'widgets.chatAccepts',
    show: false,
  },
  CHAT_AHT: {
    type: 'chatAht',
    field: 'chatAht',
    icon: 'ws-widget-chat-aht',
    locale: 'widgets.chatAht',
    show: false,
  },
  // SCORE_COUNT: {
  //   type: 'scoreCount',
  //   field: 'scoreCount',
  //   icon: 'ws-widget-score-count',
  //   locale: 'widgets.scoreCount',
  //   show: false,
  // },
  // SCORE_REQUIRED_AVG: {
  //   type: 'scoreRequiredAvg',
  //   field: 'scoreRequiredAvg',
  //   icon: 'ws-widget-score-avg',
  //   locale: 'widgets.scoreAvg',
  //   show: false,
  // },
};
