export default {
  INBOUND: {
    type: 'inbound',
    field: 'count',
    icon: 'widget-inbound',
    locale: 'widgets.inbound',
    show: true,
  },
  HANDLES: {
    type: 'handles',
    field: 'handles',
    icon: 'widget-handles',
    locale: 'widgets.handles',
    show: true,
  },
  MISSED: {
    type: 'missed',
    field: 'abandoned',
    icon: 'widget-missed',
     locale: 'widgets.missed',
    show: true,
  },
  AVG_TALK: {
    type: 'avgTalk',
    field: 'avgTalkSec',
    icon: 'widget-avg-talk',
    locale: 'widgets.avgTalk',
    show: true,
  },
  AVG_HOLD: {
    type: 'avgHold',
    field: 'avgHoldSec',
    icon: 'widget-avg-hold',
    locale: 'widgets.avgHold',
    show: true,
  },
  OCCUPANCY: {
    type: 'occupancy',
    field: 'occupancy',
    icon: 'widget-occupancy',
    locale: 'widgets.occupancy',
    show: true,
  },
  UTILIZATION: {
    type: 'utilization',
    field: 'utilization',
    icon: 'widget-utilization',
    locale: 'widgets.utilization',
    show: true,
  },
};
