name: Update lib

on:
  workflow_dispatch:
    inputs:
      package:
        description: Which library to update
        required: true
        type: choice
        options:
          - '@webitel/ui-sdk'
          - '@webitel/api-services'
          - '@webitel/flow-ui-sdk'
          - '@webitel/styleguide'
          - '@webitel/ui-datalist'

permissions:
  contents: write

jobs:
  publish:
    runs-on: [ arc-frontend-runner-set ]
    steps:
      - name: Create GitHub App token
        uses: webitel/reusable-workflows/actions/create-github-app-token@create-github-app-token-v1
        id: app-token
        with:
          client-id: ${{ vars.DELIVERY_BOT_CLIENT_ID }}
          private-key: ${{ secrets.DELIVERY_BOT_APP_PEM }}

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: true

      - name: Configure Git
        run: |
          git config user.name '${{ steps.app-token.outputs.user-name }}'
          git config user.email '${{ steps.app-token.outputs.user-email }}'

      - name: Install deps
        run: npm ci

      - name: Update selected lib
        run: |
          PKG="${{ inputs.package }}"
          npm update "$PKG"
          npm ls "$PKG"

      - name: Commit and push changes
        run: |
          PKG="${{ inputs.package }}"
          git add package.json
          if [ -f package-lock.json ]; then
            git add package-lock.json
          fi
          
          git diff --cached --quiet && exit 0
          git commit -m "chore(deps): update ${PKG}"
          git push
