name: ui-sdk.update.yml
on:
  #  https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true

      - name: Update ui-sdk
        id: update-ui-sdk

        run: |
          npm ci
          npm run utils:up-libs

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
